# Generated by Django 3.2.5 on 2021-07-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BussinessCustomer',
            fields=[
                ('bcid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=200)),
                ('cemail', models.EmailField(max_length=254)),
                ('cadd', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=20)),
                ('cpwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=200)),
                ('pcost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pmfd', models.DateField(auto_now_add=True)),
                ('pexpd', models.DateField()),
                ('quantity', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=200)),
                ('scompany', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField()),
                ('bcid', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.product')),
            ],
        ),
    ]
